---

- name: Install Nginx and things.
  yum: name={{ item }} state=present
  with_items:
   - nginx
   - aws-cli

- name: Starting the nginx service.
  service: name=nginx state=started enabled=yes

- name: Copying the index.html template to /usr/share/nginx/html
  template: src=index.html.j2 dest=/usr/share/nginx/html/index.html
